### ISSUE TITLE
This library take up too much memory

### ISSUE THREAD

**Issue by buckle2000** [tanema/light_world.lua#21]
with no object involves, only with ambient light {0,0,0}, this library's draw call takes up about 1500MB of memory.

**Comment by tanema** [comment]
You are welcome to open a pull request on how to solve it.

**Comment by Guard13007** [comment]
@tanema Do you know what uses the most memory? Or how to measure? I wouldn't know where to begin.

**Comment by VideahGams** [comment]
[The problem is this function](https://github.com/tanema/light_world.lua/blob/master/lib/util.lua#L4), it's creating a new Canvas everytime it's called which never gets garbage collected and fills up memory.

**Comment by buckle2000** [comment]
@tanema please re-open this issue.
Will this help?
https://love2d.org/wiki/Canvas:newImageData

**Comment by giann** [comment]
This is a huge issue. This basically means that a new canvas is created each frame.

**Comment by buckle2000** [comment]
@giann can you test that fix?
