### ISSUE TITLE
main.lua file which run all examples is not working

### ISSUE THREAD

**Issue by gukiboy** [tanema/light_world.lua#24]
Due to some code change, method `drawShadows()` at file `init.lua` fails on line `160:self.shadowShader:send('lightRange',{light.range * s})`.

This happens because `self.shadowShader:send()` should receive a number instead of a table.
Changing the line to `160:self.shadowShader:send('lightRange',light.range * s)` solves the issue.

Screenshot attached.
![love2dlight](https://cloud.githubusercontent.com/assets/4400335/20546153/949187dc-b0fa-11e6-8476-4f5c80bff8ad.png)

**Comment by tanema** [comment]
If you know how to solve the issue, please open a pull request. Thank you for your contribution.

**Comment by gukiboy** [comment]
I've opened a pull request.
You're welcome!
