### ISSUE TITLE
Incorrect normal map vertically

### ISSUE THREAD

**Issue by demipixel** [tanema/light_world.lua#26]
I just downloaded the examples to test this out and it seems that when shining light on an object with a normal map, the light is on the correct size on the x-axis (left and right), however if the light is below the object, the top half lights up, and vice-verca.

**Comment by demipixel** [comment]
Temp fix by changing body.lua:573 to

```
if self.type == 'animation' then
      self.animation:draw(self.normal, self.x, self.y, self.rotation, self.scalex, -self.scaley, self.nx, self.ny)
    else
      love.graphics.draw(self.normalMesh, self.x, self.y, self.rotation, self.scalex, -self.scaley, self.nx, self.ny)
    end
```

(self.scaley => -self.scaley)

but blopp.png is still wrong (is that a generated map?)

**Comment by punk0x29a** [comment]
Hi,
https://github.com/tanema/light_world.lua/issues/23 << check out this issue, it sounds like the same problem
