### ISSUE TITLE
Extremely low performance

### ISSUE THREAD

**Issue by punk0x29a** [tanema/light_world.lua#27]
Hi there,
I'm not sure what can be done regarding the performance issue with this library...
When working with large scenes (few thousand normal-mapped objects + shadow-casting polygons) in 1080p two things happen:

1) Memory gets filled up to the point where machine starts swapping and it basically freezes within seconds. I have to call garbage collector manually to keep it around ~200MB all the time

2) Adding just a few light sources slows down game to a crawl - single digit FPS count. 
I've tried it on quite a few machines and even dedicated, high-end gaming rig had problems... 

Are there any things I should check on my side? I've noticed that the "complex" demo provided yields similar results when adding many light sources and shadow casters. It probably - _probably_ - gets around better because of much lower resolution and smaller scene size.

Thanks and happy new year!

**Comment by giann** [comment]
This lib uses shaders to display light effects. A shader is a little piece of code called *for each pixel*. The higher your resolution, the slower it will be. That being said, I heavily experimented with it on smaller resolutions and concluded that this lib should not be used with a lot of light sources. This is a little too much work for löve.

**Comment by F483** [comment]
Is there a good way to increase performance if I'm using pixel art anyway? I have an game resolution of 512x320 and scale accordingly.

**Comment by giann** [comment]
Take a look at [#29](https://github.com/tanema/light_world.lua/pull/29)

**Comment by F483** [comment]
Not exactly what I was looking for, but any performance improvement is good.
