### ISSUE TITLE
Object in shadow is still drawn

### ISSUE THREAD

**Issue by zell2002** [tanema/light_world.lua#30]
I've set ambient to black, then I run the complex demo. I left click twice(adding standard polygons) one up and to the left of the other.
When I move the light to the top left, it casts a shadow down on to the bottom object but the bottom object is still drawn (rather than being hidden) - Is this correct?
Example:
http://imgur.com/a/cdYyc

**Comment by Guard13007** [comment]
It's been a while since I used this library, so I don't remember exactly how it works, but essentially depending on whether you draw your objects before or after the shadows determines whether or not they are hidden by shadows.

**Comment by twentytwoo** [comment]
Also having this problem, see image. It's a shame since this lib looks good :(

![2017-07-25-161443_1366x768_scrot](https://user-images.githubusercontent.com/13081443/28579395-7a643bb4-7154-11e7-836b-f156764adf69.png)

**Comment by egordorichev** [comment]
Hm, works fine for me, but I want to see the bodies! Any way to reproduce?

**Comment by zell2002** [comment]
@Guard13007 that is fair.. but surely the lib should handle that? 
Would I have to rewrite parts of it? I must admit, last time I looked at it I found it a bit confusing lol.
Any pointers?

@egordorichev Can we see a screenshot of it working for you? As my screenshot is using it out the box.

**Comment by tanema** [comment]
Yeah this library is a light model and not something that culls objects. Also you might try to turn the ambient color completely black to mimic not drawing objects, however choosing to draw and not draw something is not the task of this library and is part of your own game code. Feel free to fork and alter.

**Comment by egordorichev** [comment]
@zell2002 
![screenshot from 2018-02-18 22-38-26](https://user-images.githubusercontent.com/7851390/36364792-508124a4-1557-11e8-99fb-008e46ebf2e0.png)

**Comment by Guard13007** [comment]
@zell2002 Sorry, can't say much as I haven't worked with it in a long time. Been busy with projects not using lighting.

**Comment by zell2002** [comment]
> 
> 
> @zell2002
> ![screenshot from 2018-02-18 22-38-26](https://user-images.githubusercontent.com/7851390/36364792-508124a4-1557-11e8-99fb-008e46ebf2e0.png)

Is this using the same library? Did you have to change the code/world config?
