### ISSUE TITLE
rotation?

### ISSUE THREAD

**Issue by DarkShroom** [tanema/light_world.lua#32]
I assume this does not seem to support rotation?

does anyone have any idea how hard it would be to implement rotation?

**Comment by tanema** [comment]
Why do you assume that? I haven't touched this code in a while but I remember I working on every graphic translation. Have you tried it?

**Comment by DarkShroom** [comment]
i couldn’t find any functions like:

lightWorld:rotate
lightWorld:setRotation etc, i tried looking in the code

on the main page of the gitHub we have:

function love.update(dt)
  lightWorld:update(dt)
  lightWorld:setTranslation(x, y, scale)
end

no, mention of rotation and my scene doesn’t rotate when i use that render (which i guess it couldn’t possibly know the rotation anyway, because i can’t find a rotate function)


If i am missing something sorry, but yes i have actually built a OO design that iterates my scene objects to draw them, i have set it up with multiple render passes to test, so for the life of me i cannot find a rotate function to make the lightworld render pass follow the rotation (although i’ve got the scaling and offset following)

I can share my code if you want

**Comment by tanema** [comment]
like I said it has been a while since I have touched this lib but did you try using a regular rotation? This is also on the main page:

```
function love.draw()
  love.graphics.push()
    love.graphics.translate(x, y)
    love.graphics.scale(scale)
    lightWorld:draw(function()
      -- do your stuff
    end)
  love.graphics.pop()
end
```

Did you try using a `love.graphics.rotate` in there? This lib needs scale specifically because of how the shadows are rendered however rotation should not be a problem if everything is rotated.

**Comment by DarkShroom** [comment]
wow, thanks

it just seemed illogical to me, so if rotate was inside the:

"do your stuff bit"... it rotated.. silly me, the way i'd organised my code i had assumed the rotation would stay true through that functions bit

thanks, this is great then cheers

**Comment by tanema** [comment]
I think you should probably do the rotation outside the `lightWorld:draw` call.
