### ISSUE TITLE
Update for latest löve version (11.1)

### ISSUE THREAD

**Issue by flamendless** [tanema/light_world.lua#39]

**Comment by tanema** [comment]
Please either tell me what is broken or open a PR with fixes. I haven't touched Löve for about a year so it would be helpful to have more than a title.

**Comment by flamendless** [comment]
@tanema the change that affects all löve projects : color range values have changed from 0-255 to 0-1.

**Comment by flamendless** [comment]
Okay, I'll make a PR with fixes for 11.1
